// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCypP7nSTf2tYiTpG3ayNAR_j353lV5TtQ',
    appId: '1:381840732280:web:21f3bdf16fae1dbf5fbd8d',
    messagingSenderId: '381840732280',
    projectId: 'socialapp-7ecfd',
    authDomain: 'socialapp-7ecfd.firebaseapp.com',
    storageBucket: 'socialapp-7ecfd.appspot.com',
    measurementId: 'G-46M8NXBJ6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOushM42tuQRUckF6sCIllUCOXqTzdmI',
    appId: '1:381840732280:android:04097c746323f0ca5fbd8d',
    messagingSenderId: '381840732280',
    projectId: 'socialapp-7ecfd',
    storageBucket: 'socialapp-7ecfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6I53wZa5D30fqHWlUu9CaH1lDMZQFX2w',
    appId: '1:381840732280:ios:110197fdb414dbd25fbd8d',
    messagingSenderId: '381840732280',
    projectId: 'socialapp-7ecfd',
    storageBucket: 'socialapp-7ecfd.appspot.com',
    iosClientId: '381840732280-4giakrcnjbs7bja7it7sknjnuvppslcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamSocialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6I53wZa5D30fqHWlUu9CaH1lDMZQFX2w',
    appId: '1:381840732280:ios:36c12a78fb84cbcc5fbd8d',
    messagingSenderId: '381840732280',
    projectId: 'socialapp-7ecfd',
    storageBucket: 'socialapp-7ecfd.appspot.com',
    iosClientId: '381840732280-jb4fvunprd3d0i8j7f1t2q50gd4h5h7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.dreamSocialApp.RunnerTests',
  );
}
